# Generated by Django 3.2.3 on 2021-06-17 06:06

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BootCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('main_photo', models.FileField(upload_to='bootcamp/')),
                ('start_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('is_presence', models.BooleanField(default=False)),
                ('is_hybrid', models.BooleanField(default=False)),
            ],
        ),
    ]
