# Generated by Django 3.2.3 on 2021-06-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BootCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('main_photo', models.FileField(upload_to='bootcamp/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_presence', models.BooleanField(default=False)),
                ('is_hybrid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='BootCampRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=130)),
                ('last_name', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('want_virtual', models.BooleanField(default=False)),
                ('payment_ref_id', models.CharField(default='No Ref ID', max_length=128)),
                ('completed_payment', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bootcamp.bootcamp')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
