# Generated by Django 3.2.3 on 2021-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0002_bootcamp_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bootcamp',
            options={'ordering': ('start_date',)},
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
