# Generated by Django 3.2.3 on 2021-06-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0003_auto_20210619_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bootcamp',
            options={'ordering': ('-start_date',)},
        ),
        migrations.CreateModel(
            name='BootCampRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=130)),
                ('last_name', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('want_virtual', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bootcamp.bootcamp')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
