# Generated by Django 3.2.3 on 2021-06-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0004_auto_20210626_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampregister',
            name='completed_payment',
            field=models.BooleanField(default=False),
        ),
    ]
