# Generated by Django 3.2.3 on 2021-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0005_bootcampregister_completed_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampregister',
            name='payment_ref_id',
            field=models.CharField(default='No Ref ID', max_length=128),
        ),
    ]
