# Generated by Django 3.2.3 on 2021-06-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us Data'},
        ),
        migrations.RemoveField(
            model_name='workwithus',
            name='service',
        ),
        migrations.AddField(
            model_name='workwithus',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='work-with-us/'),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='first_name',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='last_name',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
