# Generated by Django 3.2.3 on 2021-06-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210613_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workwithus',
            options={'verbose_name_plural': 'Work with Us Data'},
        ),
    ]
